/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmabilling;

import java.awt.Color;
import java.util.Date;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


import java.text.SimpleDateFormat;  

/**
 *
 * @author CSDT
 */
public class PurchaseProuct extends javax.swing.JFrame {

    /**
     * Creates new form PurchaseProuct
     */
    public PurchaseProuct() {
        initComponents();
        PartyName();
        setProductType();
        
    }
    private void setProductType()
    {
          try
        {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct PRODUCTTYPE from PRODUCTMASTER ";
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                    txtProductType.addItem(rs.getString("PRODUCTTYPE"));
                }

        }
        catch(Exception e)
        {

        }
    }
    public void PartyName()
    {
         try
        {
            if(!txtProductType.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct PARTYNAME from SUPPLIERMASTER ";
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                    SupplierName.addItem(rs.getString("PARTYNAME"));
                }
            }

        }
        catch(Exception e)
        {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAadhar = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        SupplierName = new javax.swing.JComboBox<>();
        txtDat = new javax.swing.JTextField();
        txtInvoice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProductType = new javax.swing.JComboBox<>();
        txtProductName = new javax.swing.JComboBox<>();
        MfgName = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        SellingPrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        expDat = new javax.swing.JTextField();
        HsnCod = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtPcs = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPack = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        PurRate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        totQty = new javax.swing.JTextField();
        NetAmount = new javax.swing.JTextField();
        totalAmount = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtPay = new javax.swing.JTextField();
        txtDues = new javax.swing.JTextField();
        PayMode = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel2FocusGained(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile No.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Supplier Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Aadhar No.");

        txtAadhar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAadhar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtAadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAadharActionPerformed(evt);
            }
        });

        txtMobile.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtMobile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });

        SupplierName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        SupplierName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        SupplierName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SupplierNameItemStateChanged(evt);
            }
        });

        txtDat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtDat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDatFocusGained(evt);
            }
        });
        txtDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatActionPerformed(evt);
            }
        });

        txtInvoice.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInvoice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInvoiceFocusGained(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Invoice No.");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Invoice Date");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddress)
                    .addComponent(SupplierName, 0, 160, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(txtAadhar))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(SupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Type");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mfg. Name");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity");

        txtProductType.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtProductType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtProductTypeItemStateChanged(evt);
            }
        });

        txtProductName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtProductName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtProductName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtProductNameItemStateChanged(evt);
            }
        });
        txtProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductNameActionPerformed(evt);
            }
        });

        MfgName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        MfgName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MfgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfgNameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Selling Price");

        SellingPrice.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        SellingPrice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SellingPrice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SellingPriceFocusGained(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("HSN Code");

        expDat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        expDat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        expDat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expDatFocusGained(evt);
            }
        });
        expDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expDatActionPerformed(evt);
            }
        });

        HsnCod.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        HsnCod.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HsnCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HsnCodActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Exp. Date");

        txtPcs.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPcs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPcsActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Pack");

        txtPack.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPack.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPackFocusGained(evt);
            }
        });
        txtPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPackActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(0, 102, 204));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        PurRate.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        PurRate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MRP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel18)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(HsnCod)
                                .addComponent(txtProductType, 0, 156, Short.MAX_VALUE))
                            .addComponent(PurRate, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel19))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtProductName, 0, 172, Short.MAX_VALUE)
                            .addComponent(expDat)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPcs, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(161, 161, 161))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MfgName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(txtPack))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(MfgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HsnCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(expDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PurRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        tab.setBackground(new java.awt.Color(255, 255, 153));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Type", "Product Name", "Mfg. Name", "HSN Code", "Exp. Date", "Pack", "Pcs", "Mrp", "Selling Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 0));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Pcs");
        jLabel14.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Total Amount");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Net Amount");

        totQty.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        totQty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        totQty.setEnabled(false);

        NetAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        NetAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NetAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetAmountActionPerformed(evt);
            }
        });

        totalAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        totalAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        totalAmount.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NetAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(totalAmount))
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totQty, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(totQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(NetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 0));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Pay Amount");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Payment Mode");
        jLabel22.setEnabled(false);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Dues Amount");

        txtPay.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPay.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPayFocusLost(evt);
            }
        });
        txtPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayActionPerformed(evt);
            }
        });

        txtDues.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtDues.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDues.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuesFocusGained(evt);
            }
        });

        PayMode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PayMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Paytm", "Cheque" }));
        PayMode.setEnabled(false);

        SaveButton.setBackground(new java.awt.Color(0, 153, 0));
        SaveButton.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.setEnabled(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDues)
                    .addComponent(PayMode, 0, 104, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDues, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Purchase Product");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 712, Short.MAX_VALUE))))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAadharActionPerformed
    String path="jdbc:derby://localhost:1527/Pharma";
     String name="abc";
     String pass="abc";
    private void txtProductTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtProductTypeItemStateChanged
        try
        {
            if(!txtProductType.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct PRODUCTNAME from PRODUCTMASTER where PRODUCTTYPE='"+txtProductType.getSelectedItem().toString()+"' ";
                
                ResultSet rsTemp=st.executeQuery(str);
                txtProductName.removeAll();
                txtProductName.removeAllItems();
                
                
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                    txtProductName.addItem(rs.getString("PRODUCTNAME"));
                }
            }

        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductTypeItemStateChanged

    private void txtProductNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtProductNameItemStateChanged
        try
        {
            if(!txtProductName.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct MFGNAME,HSNCODE,MRP from PRODUCTMASTER where PRODUCTTYPE='"
                        +txtProductType.getSelectedItem().toString()
                        +"' and PRODUCTNAME='"+txtProductName.getSelectedItem().toString()+"' ";
                
                ResultSet rs=st.executeQuery(str);
                if(rs.next())
                {
                    MfgName.setText(rs.getString("MFGNAME"));
                    HsnCod.setText(rs.getString("HSNCODE"));
                    PurRate.setText(rs.getString("MRP"));
                }
                
               String str2="select Distinct SELLINGPRICE,HSNCODE from STOCKMASTER where HSNCODE='"+HsnCod.getText()+"' ";
               
                ResultSet rs2=st.executeQuery(str2);
                if(rs2.next())
                {
                   
                   SellingPrice.setText(rs2.getString("SELLINGPRICE"));
                }
                
            }

        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameItemStateChanged

    private void MfgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MfgNameActionPerformed
    public void Totalsum()
    {
        DefaultTableModel model=(DefaultTableModel)tab.getModel();
        int rows=tab.getRowCount();
        int sum=0; int netSum=0; int pcsSum=0;
        for(int i=0;i<rows;i++)
        {
           int sum1=Integer.parseInt(tab.getValueAt(i, 9).toString());
           int sum2=Integer.parseInt(tab.getValueAt(i, 6).toString());
            sum=sum1;
            String tot=String.valueOf(sum);
            netSum=netSum+sum;
            totalAmount.setText(tot);
            
            
            pcsSum=sum2+pcsSum;
        }
        NetAmount.setText(String.valueOf(netSum));
        totQty.setText(String.valueOf(pcsSum));
    }
    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        long t=System.currentTimeMillis();
        Date dd=new Date(t);
        Time tim=new Time(t);
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MMM-YYYY");
        txtDat.setText(sdf.format(dd));
        
        
        SimpleDateFormat sdf2=new SimpleDateFormat("ddMMYYHHmmss");
        Date date=new Date();
        txtInvoice.setText(sdf2.format(date));
        
        
        SimpleDateFormat sdf3=new SimpleDateFormat("YYYY");
        Date date2=new Date();
        expDat.setText(String.valueOf(Integer.parseInt(sdf3.format(date2))+10));
        

            try
            {
                    
                    if("".equals(PurRate.getText())
                            ||"".equals(txtPcs.getText())
                            ||"Selected".equals(SupplierName.getSelectedItem())
                            ||"".equals(txtDat.getText())
                            ||"Select".equals(txtProductName.getSelectedItem())
                            ||"Select".equals(txtProductType.getSelectedItem())                            
                            ||"".equals(expDat.getText())
                            ||"".equals(txtInvoice.getText())
                            
                            
                            ){
                                JOptionPane.showMessageDialog(null, "Please fill all the required fields");
                    }else{
                        int qty=Integer.parseInt(txtPcs.getText());
                        //int pack=Integer.parseInt(txtPack.getText());
                        int rate=Integer.parseInt(PurRate.getText());
                        int Amount=qty*rate;
                   
        
                        DefaultTableModel model=(DefaultTableModel)tab.getModel();
                        model.addRow(new Object[]{txtProductType.getSelectedItem(),txtProductName.getSelectedItem(),MfgName.getText(),HsnCod.getText(),expDat.getText(),txtPack.getText(),txtPcs.getText(),PurRate.getText(),SellingPrice.getText(),Amount});
                
                    }
                 
                    
                Totalsum();
                txtPay.setText(NetAmount.getText());
                txtDues.setText("0");
                SaveButton.setEnabled(true);
            }
            
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Error: "+e);
            }
            

        
//        MfgName.setText("");
//        PurRate.setText("");
//        SellingPrice.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed
    private void saveData()
    {
         try
        {
            Connection con=DriverManager.getConnection(path,name,pass);
            Statement st=con.createStatement();
            

            
                   
                    String str1 = "Select PREVDUES from SUPPLIERMASTER where PARTYNAME='"+SupplierName.getSelectedItem()+"' ";
                    ResultSet rs=st.executeQuery(str1);
                    if(rs.next())
                    {
                        int dues=Integer.parseInt(rs.getString("PREVDUES"));
                        int duesNew=Integer.parseInt(txtDues.getText());
                        int totDues=dues+duesNew;
                        if(dues>0)
                        {
                            
                            int total=dues+duesNew;
                            String total1=String.valueOf(total);
                             
                            String str3="Update SUPPLIERMASTER set PREVDUES='"+total1+"' where PARTYNAME='"+SupplierName.getSelectedItem()+"' ";
                            st.execute(str3);
                        }
                        else
                        {            
                              String str5="Update SUPPLIERMASTER set PREVDUES='"+txtDues.getText()+"' where PARTYNAME='"+SupplierName.getSelectedItem()+"' ";
                              st.execute(str5);
                        }
                        
                        
                        
                        
                        String str="insert into PURCHASEBILL values('"+txtInvoice.getText()+"','"+txtDat.getText()+"','"+SupplierName.getSelectedItem()+"','"+totQty.getText()+"','"+totalAmount.getText()+"','"+NetAmount.getText()+"','"+txtPay.getText()+"','"+txtDues.getText()+"','"+PayMode.getSelectedItem().toString()+"')";
                        st.execute(str);                        
                    }
                    
                    int rows=tab.getRowCount();  
                    for(int i=0;i<rows;i++)
                    {
                      
                                String str8="insert into PURCHASEPRODUCT values('"+txtInvoice.getText()+"','"+txtDat.getText()+"','"+SupplierName.getSelectedItem()+"','"+tab.getValueAt(i,0).toString()+"','"+tab.getValueAt(i,1).toString()+"','"+tab.getValueAt(i,2).toString()+"','"+tab.getValueAt(i,3).toString()+"','"+tab.getValueAt(i,4).toString()+"','"+tab.getValueAt(i,5).toString()+"','"+tab.getValueAt(i,6).toString()+"','"+tab.getValueAt(i,7).toString()+"','"+tab.getValueAt(i,8).toString()+"','"+tab.getValueAt(i,9).toString()+"')";
                                st.execute(str8);
                                
                                
//                                String str9="Select PACK,PCS,SELLINGPRICE,AMOUNT from STOCKMASTER where PRODUCTTYPE='"+tab.getValueAt(i,0).toString()
//                                        +"'  and PRODUCTNAME='"+tab.getValueAt(i,1).toString()+"' "
//                                        +" and MFGNAME='"+tab.getValueAt(i,2).toString()+"' "
//                                        +" and HSNCODE='"+tab.getValueAt(i,3).toString()+"' ";

                                String str9="Select PACK,PCS,SELLINGPRICE,AMOUNT from STOCKMASTER "
                                        +"where PRODUCTNAME='"+tab.getValueAt(i,1).toString()+"' "
                                        +" and MFGNAME='"+tab.getValueAt(i,2).toString()+"' ";
                                
                                ResultSet rs1=st.executeQuery(str9);
                                if(rs1.next())
                                {
                                
                                    int Qty=Integer.parseInt(rs1.getString("PACK"));
                                    int Qty1=Integer.parseInt(tab.getValueAt(i,5).toString());
                                    int totalQty=Qty+Qty1;
                                    //String tQty=String.valueOf(totalQty);
                                    
                                    int pcs=Integer.parseInt(rs1.getString("PCS"));
                                    int pcs1=Integer.parseInt(tab.getValueAt(i,6).toString());
                                    int totpcs=pcs+pcs1;
                                    //String totPcs=String.valueOf(totpcs);
                                    
//                                   int Rat=Integer.parseInt(tab.getValueAt(i,7).toString());
//                                   String trat=String.valueOf(Rat);
                                   
                                    int totAm=Integer.parseInt(rs1.getString("AMOUNT")); //amount from stockmaster
                                    int Amont=Integer.parseInt(tab.getValueAt(i,9).toString()); //from GUI table
                                    int totAmount=totAm+Amont;
                                     //String tAmount=String.valueOf(totAmount);
                                     
                                    String str10="Update STOCKMASTER set PACK='"+String.valueOf(totalQty)
                                            +"',PCS='"+String.valueOf(totpcs)
                                            +"', AMOUNT='"+String.valueOf(totAmount)+" ' "
                                           
                                            +" where PRODUCTTYPE=' "+tab.getValueAt(i,0).toString()
                                            +"'  and MFGNAME='"+tab.getValueAt(i,2).toString()+"' ";
                                    st.execute(str10);
                                }
                                else
                                {
                                    String str11=" insert into STOCKMASTER values(' "+tab.getValueAt(i,0).toString()+" ',' "+tab.getValueAt(i,1).toString()+" ',' "+tab.getValueAt(i,2).toString()+"','"+tab.getValueAt(i,3).toString()+"','"+tab.getValueAt(i,4).toString()+"','"+tab.getValueAt(i,5).toString()+"','"+tab.getValueAt(i,6).toString()+"','"+tab.getValueAt(i,7).toString()+"','"+tab.getValueAt(i,8).toString()+"','"+tab.getValueAt(i,9).toString()+"')";
                                    st.execute(str11);
                                }
                    }
                   
        }
        catch(Exception e)
        {
                 JOptionPane.showMessageDialog(null,"Error!"+e);  
           
        }
         JOptionPane.showMessageDialog(this,"Save Successfully");
    }
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        if(tab.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this,"Fields empty");
        }
        else
        {
            saveData();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void SupplierNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_SupplierNameItemStateChanged
        
            try
        {
            if(!txtProductType.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct AADHAR,MOBILE,ADDRESS from SUPPLIERMASTER where PARTYNAME='"+SupplierName.getSelectedItem()+"' ";
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                        txtMobile.setText(rs.getString("MOBILE"));
                         txtAddress.setText(rs.getString("ADDRESS"));
                      txtAadhar.setText(rs.getString("AADHAR"));
                     
                }
            }

        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SupplierNameItemStateChanged

    private void expDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expDatActionPerformed

    private void HsnCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HsnCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HsnCodActionPerformed

    private void txtPcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPcsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPcsActionPerformed

    private void txtPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPackActionPerformed

    private void txtPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayActionPerformed

      
    }//GEN-LAST:event_txtPayActionPerformed

    private void txtDuesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuesFocusGained
        int total=Integer.parseInt(NetAmount.getText());
        int Pay=Integer.parseInt(txtPay.getText());
        if(!"".equals(NetAmount.getText())&&!"".equals(txtPay.getText())
                &&total!=0&&total>=Pay)
        {
            int dues1=total-Pay;
            txtDues.setText(String.valueOf(dues1));
        }
    }//GEN-LAST:event_txtDuesFocusGained

    private void txtInvoiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInvoiceFocusGained
         SimpleDateFormat sdf2=new SimpleDateFormat("ddMMYYHHmmss");
        Date date=new Date();
        txtInvoice.setText(sdf2.format(date));
    }//GEN-LAST:event_txtInvoiceFocusGained

    private void jPanel2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusGained
        
    }//GEN-LAST:event_jPanel2FocusGained

    private void txtDatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatFocusGained
        long t=System.currentTimeMillis();
        Date dd=new Date(t);
        Time tim=new Time(t);
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MMM-YYYY");
        txtDat.setText(sdf.format(dd));
    }//GEN-LAST:event_txtDatFocusGained

    private void expDatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expDatFocusGained
        SimpleDateFormat sdf3=new SimpleDateFormat("YYYY");
        Date date2=new Date();
        expDat.setText(String.valueOf(Integer.parseInt(sdf3.format(date2))+10));
        
    }//GEN-LAST:event_expDatFocusGained

    private void NetAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetAmountActionPerformed

    private void txtPackFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPackFocusGained
        // TODO add your handling code here:
        txtPack.setText("1");
    }//GEN-LAST:event_txtPackFocusGained

    private void txtDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void txtPayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPayFocusLost
        // TODO add your handling code here:
        if(txtPay.getText()==""){
            txtPay.setBackground(Color.ORANGE);
        }
    }//GEN-LAST:event_txtPayFocusLost

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void SellingPriceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SellingPriceFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SellingPriceFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseProuct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseProuct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseProuct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseProuct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PurchaseProuct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField HsnCod;
    private javax.swing.JTextField MfgName;
    private javax.swing.JTextField NetAmount;
    private javax.swing.JComboBox<String> PayMode;
    private javax.swing.JTextField PurRate;
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField SellingPrice;
    private javax.swing.JComboBox<String> SupplierName;
    private javax.swing.JTextField expDat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tab;
    private javax.swing.JTextField totQty;
    private javax.swing.JTextField totalAmount;
    private javax.swing.JTextField txtAadhar;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDat;
    private javax.swing.JTextField txtDues;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtPack;
    private javax.swing.JTextField txtPay;
    private javax.swing.JTextField txtPcs;
    private javax.swing.JComboBox<String> txtProductName;
    private javax.swing.JComboBox<String> txtProductType;
    // End of variables declaration//GEN-END:variables
}
