/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmabilling;

import java.util.Date;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CSDT
 */
public class SellProduct extends javax.swing.JFrame {

    /**
     * Creates new form SellProduct
     */
    public SellProduct() {
        initComponents();
        setCustomer();
        setProductName();
    }
    private void setCustomer()
    {
        try
        {
            if(!CustomerName.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct CUSTOMERNAME from CUSTOMER ";
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                    CustomerName.addItem(rs.getString("CUSTOMERNAME"));
                }
            }

        }
        catch(Exception e)
        {

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAadhar = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        CustomerName = new javax.swing.JComboBox<>();
        txtInvoice = new javax.swing.JTextField();
        txtDat = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JComboBox<>();
        Pack = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMrp = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Amount = new javax.swing.JTextField();
        txtPack = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPcs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        Pcs = new javax.swing.JTextField();
        MfgName = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        PayAmount = new javax.swing.JTextField();
        txtDues = new javax.swing.JTextField();
        PayMode = new javax.swing.JComboBox<>();
        SaveButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        totQty = new javax.swing.JTextField();
        NetAmount = new javax.swing.JTextField();
        totalAmount = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jPanel5.setBackground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));
        jPanel2.setForeground(new java.awt.Color(255, 255, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mobile No.");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Address");

        txtAddress.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAddress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Aadhar No.");

        txtAadhar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtAadhar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtAadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAadharActionPerformed(evt);
            }
        });

        txtMobile.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtMobile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CustomerName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CustomerName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        CustomerName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CustomerNameItemStateChanged(evt);
            }
        });

        txtInvoice.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtInvoice.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtInvoiceFocusGained(evt);
            }
        });
        txtInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInvoiceActionPerformed(evt);
            }
        });

        txtDat.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtDat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDatFocusGained(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Invoice Date");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Invoice No.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(56, 56, 56)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddress)
                    .addComponent(CustomerName, 0, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtAadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(txtDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Stock Pack");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mfg. Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pack");

        txtName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        txtName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtNameItemStateChanged(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        Pack.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Pack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pack.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PackFocusGained(evt);
            }
        });
        Pack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MRP");

        txtMrp.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtMrp.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMrpActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Amount");

        Amount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Amount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Amount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AmountFocusGained(evt);
            }
        });

        txtPack.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPack.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPack.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Stock Pieces");

        txtPcs.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtPcs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPcs.setEnabled(false);
        txtPcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPcsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Pieces");

        Pcs.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        Pcs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Pcs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PcsFocusGained(evt);
            }
        });
        Pcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcsActionPerformed(evt);
            }
        });

        MfgName.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        MfgName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MfgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MfgNameActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(0, 102, 204));
        AddButton.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pack, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MfgName, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtPcs)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(Pcs, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Amount)
                            .addComponent(txtMrp)))
                    .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(MfgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(Pcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtPcs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sell  Product");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Mfg Name", "Stock Pack", "Stock Pcs", "Pack", "Pcs", "Mrp", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab);

        jPanel4.setBackground(new java.awt.Color(102, 0, 102));
        jPanel4.setForeground(new java.awt.Color(255, 255, 0));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Pay Amount");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Pay Mode");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Dues Amount");

        PayAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        PayAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PayAmount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PayAmountFocusGained(evt);
            }
        });
        PayAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayAmountActionPerformed(evt);
            }
        });
        PayAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PayAmountKeyPressed(evt);
            }
        });

        txtDues.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        txtDues.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtDues.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDuesFocusGained(evt);
            }
        });

        PayMode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PayMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Paytm", "Cheque" }));

        SaveButton.setBackground(new java.awt.Color(0, 153, 0));
        SaveButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.setEnabled(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(txtDues))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(PayMode, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(PayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(PayAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PayMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtDues, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel3.setBackground(new java.awt.Color(102, 0, 102));
        jPanel3.setForeground(new java.awt.Color(255, 255, 0));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Total Pcs");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Amount");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Net Amount");

        totQty.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        totQty.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        NetAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        NetAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        totalAmount.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        totalAmount.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalAmount))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(20, 20, 20)
                        .addComponent(NetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(totQty, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel16)
                    .addComponent(totQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NetAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setProductName()
    {
         try
        {
            if(!CustomerName.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct PRODUCTNAME from STOCKMASTER ";
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                    txtName.addItem(rs.getString("PRODUCTNAME"));
                }
            }

        }
        catch(Exception e)
        {

        }
    }
    private void txtAadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAadharActionPerformed
    String path="jdbc:derby://localhost:1527/Pharma";
     String name="abc";
     String pass="abc";
    private void CustomerNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CustomerNameItemStateChanged

        try
        {
            if(!CustomerName.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct AADHARNO,MOBILENO,ADDRESS from CUSTOMER where CUSTOMERNAME='"+CustomerName.getSelectedItem()+"' ";
                ResultSet rs=st.executeQuery(str);
                while(rs.next())
                {
                    txtMobile.setText(rs.getString("MOBILENO"));
                    txtAddress.setText(rs.getString("ADDRESS"));
                    txtAadhar.setText(rs.getString("AADHARNO"));

                }
            }

        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameItemStateChanged

    private void txtNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtNameItemStateChanged
        try
        {
            if(!txtName.equals(""))
            {
                Connection con=DriverManager.getConnection(path,name,pass);
                Statement st=con.createStatement();
                String str="select Distinct MFGNAME,PACK,PCS,MRP,SELLINGPRICE from STOCKMASTER where PRODUCTNAME='"+txtName.getSelectedItem().toString()+"' ";
                ResultSet rs=st.executeQuery(str);
                if(rs.next())
                {
                   MfgName.setText(rs.getString("MFGNAME"));
                   txtPack.setText(rs.getString("PACK"));
                   txtPcs.setText(rs.getString("PCS"));
                   txtMrp.setText(rs.getString("SELLINGPRICE"));
                }
            }

        }
        catch(Exception e)
        {

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameItemStateChanged

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void PackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PackActionPerformed

        int qty=Integer.parseInt(Pcs.getText());
        int price=Integer.parseInt(txtMrp.getText());
       // int pack=Integer.parseInt(Pack.getText());
        int amont=qty*price;
        
        Amount.setText(String.valueOf(amont));
        // TODO add your handling code here:
    }//GEN-LAST:event_PackActionPerformed

    private void txtMrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMrpActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtMrpActionPerformed

    private void txtPcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPcsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPcsActionPerformed

    private void PcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcsActionPerformed
       
        // TODO add your handling code here:
    }//GEN-LAST:event_PcsActionPerformed

    private void MfgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MfgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MfgNameActionPerformed
    private void saveData()
    {
        try
        {
            Connection con=DriverManager.getConnection(path,name,pass);
            Statement st=con.createStatement();
            String str="select PREVDUES from CUSTOMER where CUSTOMERNAME='"+CustomerName.getSelectedItem()+"' ";
            ResultSet rs=st.executeQuery(str);
            
            if(rs.next())
            {
                int dues=Integer.parseInt(rs.getString("PREVDUES"));
                int dues1=Integer.parseInt(txtDues.getText());
                int totdues=dues+dues1;
                if(dues>0)
                {
                    String str1="Update CUSTOMER set PREVDUES='"+String.valueOf(totdues)+"' where CUSTOMERNAME='"+CustomerName.getSelectedItem()+"' ";
                    st.execute(str1);
                }
                else
                {
                    String str1="Update CUSTOMER set PREVDUES='"+txtDues.getText()+"' where CUSTOMERNAME='"+CustomerName.getSelectedItem()+"' ";
                    st.execute(str1);
                }
                
                String str2="insert into SALEBILL values('"+txtInvoice.getText()+"','"+txtDat.getText()+"','"+CustomerName.getSelectedItem()+"','"+txtMobile.getText()+"','"+txtAadhar.getText()+"','"+txtAddress.getText()+"','"+totalAmount.getText()+"','"+PayMode.getSelectedItem()+"','"+PayAmount.getText()+"','"+txtDues.getText()+"')";
                st.execute(str2);
                     
               for(int i=0;i<tab.getRowCount();i++)
               {
                   String str7="insert into SALEPRODUCT values('"+txtInvoice.getText()+"','"+txtDat.getText()+"','"+CustomerName.getSelectedItem()+"','"+tab.getValueAt(i,0).toString()+"','"+tab.getValueAt(i,1).toString()+"','"+tab.getValueAt(i,2).toString()+"','"+tab.getValueAt(i,3).toString()+"','"+tab.getValueAt(i,4).toString()+"','"+tab.getValueAt(i,5).toString()+"','"+tab.getValueAt(i,6).toString()+"','"+tab.getValueAt(i,7).toString()+"')";
                   st.execute(str7);
                  
                   
                   String str8="Select PACK,PCS,AMOUNT from STOCKMASTER where  PRODUCTNAME='"+tab.getValueAt(i,0).toString()+"' and MFGNAME='"+tab.getValueAt(i,1).toString()+"' ";
                   ResultSet rs1=st.executeQuery(str8);
                   if(rs1.next())
                   {
                                     int pack=Integer.parseInt(rs1.getString("PACK"));
                                    int Pack1=Integer.parseInt(tab.getValueAt(i,4).toString());
                                    int totalQty=pack-Pack1;
                    
                                    int pcs=Integer.parseInt(rs1.getString("PCS"));
                                    int pcs1=Integer.parseInt(tab.getValueAt(i,5).toString());
                                    int totpcs=pcs-pcs1;
                          
                                     int totAm=Integer.parseInt(rs1.getString("AMOUNT"));
                                   
                                    int Amont=Integer.parseInt(tab.getValueAt(i,7).toString());
                                    int totAmount=totAm-Amont;
                 
                       String str9="Update STOCKMASTER set PACK='"+String.valueOf(totalQty)
                               +"',PCS='"+String.valueOf(totpcs)+"',AMOUNT='"+String.valueOf(totAmount)
                               +"' where PRODUCTNAME='"+tab.getValueAt(i,0).toString()
                               +"' and MFGNAME='"+tab.getValueAt(i,1).toString()+"' ";
                       st.execute(str9);
                   }
               }
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Error"+e);
        }
        
        JOptionPane.showMessageDialog(null, "Save Successfully");
    }
    
    
    public void Totalsum()
    {
       try{
        DefaultTableModel model=(DefaultTableModel)tab.getModel();
        int rows=tab.getRowCount();
        int sum=0; int netSum=0; int pcsSum=0;
        for(int i=0;i<rows;i++)
        {
           int sum1=Integer.parseInt(tab.getValueAt(i, 7).toString());
           int sum2=Integer.parseInt(tab.getValueAt(i, 5).toString());
            sum=sum1;
            String tot=String.valueOf(sum);
            netSum=netSum+sum;
            totalAmount.setText(tot);
            
            
            pcsSum=sum2+pcsSum;
        }
        NetAmount.setText(String.valueOf(netSum));
        totQty.setText(String.valueOf(pcsSum));
        
        PayAmount.setText(NetAmount.getText());
        txtDues.setText("0");
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "Error: " +e);
       }
    }
    
    
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        if(tab.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this,"Fields empty");
        }
        else
        {
           if(CustomerName.getSelectedItem()=="Select")
               JOptionPane.showMessageDialog(this, "Customer not selected");
           else
            saveData();
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed

        
        long t=System.currentTimeMillis();
        Date dd=new Date(t);
        Time tim=new Time(t);
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MMM-YYYY");
        txtDat.setText(sdf.format(dd)); 
        
        SimpleDateFormat sdf2=new SimpleDateFormat("ddMMYYHHmmss");
        Date date=new Date();
        txtInvoice.setText(sdf2.format(date));
   
        
        try
        {
            if("".equals(txtPack.getText())
                    ||"".equals(Pcs.getText())
                    ||"".equals(MfgName.getText())
                    ||"".equals(txtMrp.getText())
                    ||"".equals(Amount.getText())
                    ||"Select".equals(CustomerName.getSelectedItem())
                    
                    ){
                JOptionPane.showMessageDialog(null,"Empty Fields!!");
            }else{
                
                
            DefaultTableModel model=(DefaultTableModel)tab.getModel();
            model.addRow(new Object[]{txtName.getSelectedItem(),
                MfgName.getText(),txtPack.getText(),txtPcs.getText(),
                Pack.getText(),Pcs.getText(),txtMrp.getText(),
                Amount.getText()});
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,"Error: "+e);
        }
        
        Totalsum();
        SaveButton.setEnabled(true);
        
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_AddButtonActionPerformed

    private void PayAmountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PayAmountKeyPressed
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_PayAmountKeyPressed

    private void PayAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayAmountActionPerformed

         int total=Integer.parseInt(totalAmount.getText());
        int Pay=Integer.parseInt(PayAmount.getText());
        int dues1=total-Pay;
        txtDues.setText(String.valueOf(dues1));
            // TODO add your handling code here:
    }//GEN-LAST:event_PayAmountActionPerformed

    private void txtDatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDatFocusGained
        long t=System.currentTimeMillis();
        Date dd=new Date(t);
        Time tim=new Time(t);
        SimpleDateFormat sdf=new SimpleDateFormat("dd-MMM-YYYY");
        txtDat.setText(sdf.format(dd)); 
    }//GEN-LAST:event_txtDatFocusGained

    private void txtInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInvoiceActionPerformed

    private void txtInvoiceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtInvoiceFocusGained
         SimpleDateFormat sdf2=new SimpleDateFormat("ddMMYYHHmmss");
        Date date=new Date();
        txtInvoice.setText(sdf2.format(date));
    }//GEN-LAST:event_txtInvoiceFocusGained

    private void AmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AmountFocusGained
        if(!"".equals(txtMrp.getText())&&!"".equals(Pcs.getText()))
        {
            
            int mrp=Integer.parseInt(txtMrp.getText());
            int pcs=Integer.parseInt(Pcs.getText());
            int pack=Integer.parseInt(Pack.getText());
            int amt=mrp*pcs; 
            
            int stockPack=Integer.parseInt(txtPack.getText());
            int stockPcs=Integer.parseInt(txtPcs.getText());
            if(pcs>stockPcs)
            {
                JOptionPane.showMessageDialog(null, "Less Stock");
                Pcs.setText("0");
            }
            else if(pack>stockPcs)
            {
                JOptionPane.showMessageDialog(null, "Less Stock");
                Pack.setText("0");
            }
            else{
                 Amount.setText(String.valueOf(amt)); 
            }
        }
       
        
    }//GEN-LAST:event_AmountFocusGained

    private void PackFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PackFocusGained
        // TODO add your handling code here:
        Pack.setText("1");
    }//GEN-LAST:event_PackFocusGained

    private void txtDuesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDuesFocusGained
        
        
        if(!"".equals(NetAmount.getText())&&!"".equals(PayAmount.getText()))
        {
            int total=Integer.parseInt(NetAmount.getText());
            int Pay=Integer.parseInt(PayAmount.getText());
            int dues1=total-Pay;
            if(dues1<0)
                dues1=0;
            
            txtDues.setText(String.valueOf(dues1));
        }
        
    }//GEN-LAST:event_txtDuesFocusGained

    private void PcsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PcsFocusGained
         Pcs.setText("1");
    }//GEN-LAST:event_PcsFocusGained

    private void PayAmountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PayAmountFocusGained
        if(!"".equals(NetAmount.getText()))
        {
            PayAmount.setText(NetAmount.getText());
            txtDues.setText("0");
        }
        
    }//GEN-LAST:event_PayAmountFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SellProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SellProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SellProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SellProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SellProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField Amount;
    private javax.swing.JComboBox<String> CustomerName;
    private javax.swing.JTextField MfgName;
    private javax.swing.JTextField NetAmount;
    private javax.swing.JTextField Pack;
    private javax.swing.JTextField PayAmount;
    private javax.swing.JComboBox<String> PayMode;
    private javax.swing.JTextField Pcs;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tab;
    private javax.swing.JTextField totQty;
    private javax.swing.JTextField totalAmount;
    private javax.swing.JTextField txtAadhar;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDat;
    private javax.swing.JTextField txtDues;
    private javax.swing.JTextField txtInvoice;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtMrp;
    private javax.swing.JComboBox<String> txtName;
    private javax.swing.JTextField txtPack;
    private javax.swing.JTextField txtPcs;
    // End of variables declaration//GEN-END:variables
}
